package com.kenji1947.kenjifit.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kenji1947.kenjifit.dao.OrmExercise;
import com.kenji1947.kenjifit.dao.OrmExerciseStep;
import com.kenji1947.kenjifit.dao.OrmI18N;

import com.kenji1947.kenjifit.dao.OrmExerciseDao;
import com.kenji1947.kenjifit.dao.OrmExerciseStepDao;
import com.kenji1947.kenjifit.dao.OrmI18NDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ormExerciseDaoConfig;
    private final DaoConfig ormExerciseStepDaoConfig;
    private final DaoConfig ormI18NDaoConfig;

    private final OrmExerciseDao ormExerciseDao;
    private final OrmExerciseStepDao ormExerciseStepDao;
    private final OrmI18NDao ormI18NDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ormExerciseDaoConfig = daoConfigMap.get(OrmExerciseDao.class).clone();
        ormExerciseDaoConfig.initIdentityScope(type);

        ormExerciseStepDaoConfig = daoConfigMap.get(OrmExerciseStepDao.class).clone();
        ormExerciseStepDaoConfig.initIdentityScope(type);

        ormI18NDaoConfig = daoConfigMap.get(OrmI18NDao.class).clone();
        ormI18NDaoConfig.initIdentityScope(type);

        ormExerciseDao = new OrmExerciseDao(ormExerciseDaoConfig, this);
        ormExerciseStepDao = new OrmExerciseStepDao(ormExerciseStepDaoConfig, this);
        ormI18NDao = new OrmI18NDao(ormI18NDaoConfig, this);

        registerDao(OrmExercise.class, ormExerciseDao);
        registerDao(OrmExerciseStep.class, ormExerciseStepDao);
        registerDao(OrmI18N.class, ormI18NDao);
    }
    
    public void clear() {
        ormExerciseDaoConfig.getIdentityScope().clear();
        ormExerciseStepDaoConfig.getIdentityScope().clear();
        ormI18NDaoConfig.getIdentityScope().clear();
    }

    public OrmExerciseDao getOrmExerciseDao() {
        return ormExerciseDao;
    }

    public OrmExerciseStepDao getOrmExerciseStepDao() {
        return ormExerciseStepDao;
    }

    public OrmI18NDao getOrmI18NDao() {
        return ormI18NDao;
    }

}
