package com.kenji1947.kenjifit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORM_EXERCISE".
 */
public class OrmExercise {

    private Long id;
    private String SERVER_ID;
    private String ICON_URL;
    private Integer PERFORMANCE;
    private String TYPE_NAME;
    private Integer WEIGHT;
    private Integer WEIGHT_FOR_FEMALE;
    private Integer PM_COEFFICIENTS_STR;
    private String MUSCLE_GROUP_SERVER_ID;
    private Integer NAME_ID;
    private Integer DESCRIPTION_ID;

    public OrmExercise() {
    }

    public OrmExercise(Long id) {
        this.id = id;
    }

    public OrmExercise(Long id, String SERVER_ID, String ICON_URL, Integer PERFORMANCE, String TYPE_NAME, Integer WEIGHT, Integer WEIGHT_FOR_FEMALE, Integer PM_COEFFICIENTS_STR, String MUSCLE_GROUP_SERVER_ID, Integer NAME_ID, Integer DESCRIPTION_ID) {
        this.id = id;
        this.SERVER_ID = SERVER_ID;
        this.ICON_URL = ICON_URL;
        this.PERFORMANCE = PERFORMANCE;
        this.TYPE_NAME = TYPE_NAME;
        this.WEIGHT = WEIGHT;
        this.WEIGHT_FOR_FEMALE = WEIGHT_FOR_FEMALE;
        this.PM_COEFFICIENTS_STR = PM_COEFFICIENTS_STR;
        this.MUSCLE_GROUP_SERVER_ID = MUSCLE_GROUP_SERVER_ID;
        this.NAME_ID = NAME_ID;
        this.DESCRIPTION_ID = DESCRIPTION_ID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSERVER_ID() {
        return SERVER_ID;
    }

    public void setSERVER_ID(String SERVER_ID) {
        this.SERVER_ID = SERVER_ID;
    }

    public String getICON_URL() {
        return ICON_URL;
    }

    public void setICON_URL(String ICON_URL) {
        this.ICON_URL = ICON_URL;
    }

    public Integer getPERFORMANCE() {
        return PERFORMANCE;
    }

    public void setPERFORMANCE(Integer PERFORMANCE) {
        this.PERFORMANCE = PERFORMANCE;
    }

    public String getTYPE_NAME() {
        return TYPE_NAME;
    }

    public void setTYPE_NAME(String TYPE_NAME) {
        this.TYPE_NAME = TYPE_NAME;
    }

    public Integer getWEIGHT() {
        return WEIGHT;
    }

    public void setWEIGHT(Integer WEIGHT) {
        this.WEIGHT = WEIGHT;
    }

    public Integer getWEIGHT_FOR_FEMALE() {
        return WEIGHT_FOR_FEMALE;
    }

    public void setWEIGHT_FOR_FEMALE(Integer WEIGHT_FOR_FEMALE) {
        this.WEIGHT_FOR_FEMALE = WEIGHT_FOR_FEMALE;
    }

    public Integer getPM_COEFFICIENTS_STR() {
        return PM_COEFFICIENTS_STR;
    }

    public void setPM_COEFFICIENTS_STR(Integer PM_COEFFICIENTS_STR) {
        this.PM_COEFFICIENTS_STR = PM_COEFFICIENTS_STR;
    }

    public String getMUSCLE_GROUP_SERVER_ID() {
        return MUSCLE_GROUP_SERVER_ID;
    }

    public void setMUSCLE_GROUP_SERVER_ID(String MUSCLE_GROUP_SERVER_ID) {
        this.MUSCLE_GROUP_SERVER_ID = MUSCLE_GROUP_SERVER_ID;
    }

    public Integer getNAME_ID() {
        return NAME_ID;
    }

    public void setNAME_ID(Integer NAME_ID) {
        this.NAME_ID = NAME_ID;
    }

    public Integer getDESCRIPTION_ID() {
        return DESCRIPTION_ID;
    }

    public void setDESCRIPTION_ID(Integer DESCRIPTION_ID) {
        this.DESCRIPTION_ID = DESCRIPTION_ID;
    }

}
