package com.kenji1947.kenjifit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORM_EXERCISE_STEP".
 */
public class OrmExerciseStep {

    private Long id;
    private String ICON_URL;
    private Integer DESCRIPTION_ID;
    private Integer EXERCISE_ID;

    public OrmExerciseStep() {
    }

    public OrmExerciseStep(Long id) {
        this.id = id;
    }

    public OrmExerciseStep(Long id, String ICON_URL, Integer DESCRIPTION_ID, Integer EXERCISE_ID) {
        this.id = id;
        this.ICON_URL = ICON_URL;
        this.DESCRIPTION_ID = DESCRIPTION_ID;
        this.EXERCISE_ID = EXERCISE_ID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getICON_URL() {
        return ICON_URL;
    }

    public void setICON_URL(String ICON_URL) {
        this.ICON_URL = ICON_URL;
    }

    public Integer getDESCRIPTION_ID() {
        return DESCRIPTION_ID;
    }

    public void setDESCRIPTION_ID(Integer DESCRIPTION_ID) {
        this.DESCRIPTION_ID = DESCRIPTION_ID;
    }

    public Integer getEXERCISE_ID() {
        return EXERCISE_ID;
    }

    public void setEXERCISE_ID(Integer EXERCISE_ID) {
        this.EXERCISE_ID = EXERCISE_ID;
    }

}
