package com.kenji1947.kenjifit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORM_I18_N".
 */
public class OrmI18N {

    private Long id;
    private String RU;
    private String EN;

    public OrmI18N() {
    }

    public OrmI18N(Long id) {
        this.id = id;
    }

    public OrmI18N(Long id, String RU, String EN) {
        this.id = id;
        this.RU = RU;
        this.EN = EN;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRU() {
        return RU;
    }

    public void setRU(String RU) {
        this.RU = RU;
    }

    public String getEN() {
        return EN;
    }

    public void setEN(String EN) {
        this.EN = EN;
    }

}
